### ISSUE TITLE
Can't boot Arch

### ISSUE THREAD

**Issue by NTBBloodbath** [xeffyr/alpine-term#36] opened 2020-10-20 15:12 UTC
- [ ] Application bug: misbehaving of terminal emulator frontend.
- [x] OS bug: boot issues and system misconfiguration.

**Problem description:**
When trying to boot Arch, it reaches the start of the Journal Service and times out so it fails

**Steps to reproduce:**
Download the latest arch image provided and try to boot it

**Expected behavior:**
Arch should boot fine

**Example output**:
```
[FAILED] Failed to start Journal Service.
See 'systemctl status systemd-journald.service' for details.
[DEPEND] Dependency failed for Flus…Journal to Persistent Storage.
[  OK  ] Stopped Journal Service.
         Starting Journal Service...
[FAILED] Failed to start Rule-based…r for Device Events and Files.
See 'systemctl status systemd-udevd.service' for details.
[  OK  ] Stopped Rule-based Manager for Device Events and Files.
         Starting Rule-based Manage…for Device Events and Files...
```

**Comment by xeffyr** [comment] 2020-10-20 19:39
Are you sure that downloaded image is not corrupted?

I can't reproduce the issue. Also guy from https://github.com/xeffyr/alpine-term/issues/34 seems was able to boot it too, yet got issue with DNS which I can't confirm too.

**Comment by NTBBloodbath** [comment] 2020-10-20 19:57
> Are you sure that downloaded image is not corrupted?

I think so. Anyway I'll download again to finish to be sure

**Comment by xeffyr** [comment] 2020-10-20 20:32
To be sure that image is correct, you can verify its checksum:
```
b6a0899056e8d86d71d1f5ba306dc658267cdc6414086e5ec3e64b4d1494b399  archlinux-alpine-term-r2020.10.18.qcow2
```

I have double checked it on my device:
![merged-screens](https://user-images.githubusercontent.com/25881154/96640526-f8957d00-132b-11eb-99ff-58173ac03dda.png)
The only issue I have found is `dhcpcd` service timeout, but can be easily fixed by `systemctl start dhcpcd`.

**Comment by NTBBloodbath** [comment] 2020-10-20 22:12
> To be sure that image is correct, you can verify its checksum:
I downloaded it again and verified the checksum and it was fine, but the same error keeps happening 😔

**Comment by xeffyr** [comment] 2020-10-20 23:49
Then I can only suggest to try a previous image: https://github.com/xeffyr/alpine-term/releases/download/v13.0/archlinux-alpine-term-r2020.09.13.qcow2

As you saying that it errors due to [time out](https://github.com/xeffyr/alpine-term/issues/36#issue-725696300), I can assume that this is because your device is too slow.

Provided alternate images are not guaranteed to be 100% usable. GNU libc + systemd is quite bad combo to run in QEMU. That's actually the reason why this application uses Alpine Linux.

**Closed by xeffyr** 2020-10-20 23:49 UTC
