### ISSUE TITLE
Crash while boot

### ISSUE THREAD

**Issue by BardiaMGTGC** [xeffyr/alpine-term#35] opened 2020-10-18 06:11 UTC
So with the new patch(currently boots and doesnt just crash at the start) alpine-term crashes while booting after a certain point(Setting system lock using the hardware clock after loading modules) the signal 9 happens 

i will leave a screenshot down the issue

Phone specs: Galaxy alpha(G850F)
running lineage os 14 
armv7
2GB of ram(1.8 usable)

same thing happens with standard build but a little later on

![photo_2020-10-18_09-39-33](https://user-images.githubusercontent.com/38596879/96360030-f6fa6800-1125-11eb-9d2f-934d99818102.jpg)

**Comment by xeffyr** [comment] 2020-10-18 11:31
As I can't reproduce that, I'll assume that this is all due to unique combination of device + custom ROM + usage scheme. There also possibility that your ROM just leaks memory and OS tries to free as much RAM as possible to keep system stable. Regardless of actual case, this behavior is not normal.

Try to limit memory usage like shown in https://imgur.com/a/WmP774E:
1. Open app.
2. Immediately tap "ESC".
3. Switch to QEMU monitor session and type:
   ```
   balloon 300
   system_reset
   ```
   this will limit RAM use to 300 MiB.
4. Switch back to serial console.

Ensure that you do not use any device "boosters", "optimizers", "cleaners" or any other application thinking it can manage resources better than operating system.

I can't suggest anything else and this issue really wontfix.

**Closed by xeffyr** 2020-10-18 11:31 UTC

**Comment by BardiaMGTGC** [comment] 2020-10-18 12:22
also tested on a galaxy a5 2016 stock rom same result

**Comment by xeffyr** [comment] 2020-10-18 13:50
So far only you have reported that it crash during runtime which points on a *one* of these 2 cases:
* You have done some special device setup, e.g. installed optimizer app which kills apps running in background to "prolong battery life".
* You are running something heavy among with Alpine Term, e.g. web browser with 10+ opened tabs.

Works perfectly on my devices (ARM 32bit, 64bit). Even on Nexus 7 which has worse stats than Galaxy A5 it boots and works perfectly yet slow.
![Devices](https://user-images.githubusercontent.com/25881154/96368692-f2ea3c80-115d-11eb-9016-6be9437a76ad.jpg)

Virtual devices (x86, RAM: 1.5G, 2G) work fine too.
![AVD](https://user-images.githubusercontent.com/25881154/96369189-36927580-1161-11eb-947a-cb5719810243.png)
